import {
    DiscordMessageSlint as DiscordMessage,
    DiscordMessageKindSlint as DiscordMessageKind,
} from "../../../Models/DiscordMessage.slint";
import { LazyImage } from "../../../Models/LazyImage.slint";
import { DefaultMessage } from "Kind/DefaultMessage.slint";
import { Palette, VerticalBox } from "std-widgets.slint";
import { GuildMemberJoinView } from "Kind/GuildMemberJoin.slint";

export component MessageView inherits Rectangle {
    in-out property <DiscordMessage> message;
    in-out property <bool> has-hover: false;
    callback show-image(images: [LazyImage], index: int);

    background: has-hover || touch.has-hover ? Palette.background.brighter(0.2) : Palette.background;

    VerticalBox {
        if message.kind == DiscordMessageKind.Default || message.kind == DiscordMessageKind.Reply: DefaultMessage {
            message: message;
            show-image(images, index) => {
                root.show-image(images, index);
            }

            changed has-hover => {
                root.has-hover = self.has-hover;
            }
        }

        if message.kind == DiscordMessageKind.GuildMemberJoin: GuildMemberJoinView {
            message: message;
        }
    }

    touch := TouchArea {
        z: -1;
    }
}
