import { LazyImage } from "LazyImage.slint";

export enum DiscordMessageKindSlint {
    Default,                                 // 0
    RecipientAdd,                            // 1
    RecipientRemove,                         // 2
    Call,                                    // 3
    ChannelNameChange,                       // 4
    ChannelIconChange,                       // 5
    ChannelPinnedMessage,                    // 6
    GuildMemberJoin,                         // 7
    UserPremiumGuildSubscription,            // 8
    UserPremiumGuildSubscriptionTier1,       // 9
    UserPremiumGuildSubscriptionTier2,       // 10
    UserPremiumGuildSubscriptionTier3,       // 11
    ChannelFollowAdd,                        // 12
    GuildDiscoveryDisqualified,              // 14
    GuildDiscoveryRequalified,               // 15
    GuildDiscoveryGracePeriodInitialWarning, // 16
    GuildDiscoveryGracePeriodFinalWarning,   // 17
    ThreadCreated,                           // 18
    Reply,                                   // 19
    ChatInputCommand,                        // 20
    ThreadStarterMessage,                    // 21
    GuildInviteReminder,                     // 22
    ContextMenuCommand,                      // 23
    AutoModerationAction,                    // 24
    RoleSubscriptionPurchase,                // 25
    InteractionPremiumUpsell,                // 26
    StageStart,                              // 27
    StageEnd,                                // 28
    StageSpeaker,                            // 29
    StageRaiseHand,                          // 30
    StageTopic,                              // 31
    GuildApplicationPremiumSubscription,     // 32
    PremiumReferral,                         // 35
    GuildIncidentAlertModeEnabled,           // 36
    GuildIncidentAlertModeDisabled,          // 37
    GuildIncidentReportRaid,                 // 38
    GuildIncidentReportFalseAlarm,           // 39
    GuildDeadchatRevivePrompt,               // 40
    CustomGift,                              // 41
    GuildGamingStatsPrompt,                  // 42
    PurchaseNotification,                    // 44
    PollResult,                              // 46
    Changelog,                               // 47
    NitroNotification,                       // 48
    ChannelLinkedToLobby,                    // 49
    GiftingPrompt,                           // 50
    InGameMessageNux,                        // 51
    GuildJoinRequestAcceptNotification,      // 52
    GuildJoinRequestRejectNotification,      // 53
    GuildJoinRequestWithdrawnNotification,   // 54
    HdStreamingUpgraded,                     // 55
    ReportToModDeletedMessage,               // 58
    ReportToModTimeoutUser,                  // 59
    ReportToModKickUser,                     // 60
    ReportToModBanUser,                      // 61
    ReportToModClosedReport,                 // 62
    EmojiAdded,                              // 63
}

export struct MessageAuthorSlint {
    id: string,
    name: string,
    avatar: LazyImage,

    has_role_color: bool,
    role_color: brush,
}

export struct ReferencedMessageSlint {
    id: string,
    channel_id: string,
    guild_id: string,
    author: MessageAuthorSlint,
    content: styled-text,
    timestamp: string,
    edited_timestamp: string,
}

export struct DiscordMessageSlint {
    id: string,
    channel_id: string,
    guild_id: string,
    author: MessageAuthorSlint,
    content: styled-text,
    empty: bool,
    timestamp: string,
    edited_timestamp: string,
    referenced_message: ReferencedMessageSlint,
    kind: DiscordMessageKindSlint,
    image_attachments: [LazyImage],
}