import { DiscordChannelSlint as DiscordChannel, DiscordChannelKindSlint as DiscordChannelKind } from "../Models/DiscordChannel.slint";
import { DiscordMessageSlint as DiscordMessage, DiscordMessageKindSlint as DiscordMessageKind, MessageAuthorSlint as MessageAuthor } from "../Models/DiscordMessage.slint";
import { Icon, IconSet } from "../Libraries/lucide.slint";

export global ChannelStore {
    in-out property <[DiscordChannel]> channels;
    // in-out property <[DiscordChannel]> channels: [
    //     {
    //         id: "1",
    //         name: "bruh",
    //     },
    //     {
    //         id: "2",
    //         name: "cuh",
    //     }
    // ];

    in-out property <DiscordChannel> current_channel;

    in-out property <[DiscordMessage]> messages;

    // in-out property <[DiscordMessage]> messages: [
    //     {
    //         id: "0",
    //         content: @markdown("Loading messages..."),
    //         guild_id: "0",
    //         channel_id: "0",
    //         author: {
    //             id: "0",
    //             name: "Loading...",
    //             avatar: {
    //                 url: "bruh",
    //                 image: @image-url("../images/paicord_icon.png"),
    //                 loaded: true,
    //             },
    //             has_role_color: false,
    //             role_color: Colors.aliceblue,
    //         },
    //         timestamp: "yesteday at 12:00 PM",
    //         edited_timestamp: "",
    //         referenced_message: {
    //             id: "0",
    //             channel_id: "0",
    //             guild_id: "0",
    //             author: {
    //                 id: "0",
    //                 name: "Loading...",
    //                 avatar: {
    //                     url: "bruh",
    //                     image: @image-url("../images/paicord_icon.png"),
    //                     loaded: true,
    //                 },
    //                 has_role_color: false,
    //                 role_color: Colors.aliceblue,
    //             },
    //             content: @markdown("Loading..."),
    //             timestamp: "yesteday at 12:00 PM",
    //             edited_timestamp: "",
    //          },
    //         kind: DiscordMessageKind.Default,
    //     },
    //     {
    //         id: "0",
    //         content: @markdown("Loading messages..."),
    //         guild_id: "0",
    //         channel_id: "0",
    //         author: {
    //             id: "0",
    //             name: "Loadingaaaaaa...",
    //             avatar: {
    //                 url: "bruh",
    //                 image: @image-url("../images/paicord_icon.png"),
    //                 loaded: true,
    //             },
    //             has_role_color: false,
    //             role_color: Colors.aliceblue,
    //         },
    //         timestamp: "yesteday at 12:00 PM",
    //         edited_timestamp: "",
    //         referenced_message: {
    //             id: "0",
    //             channel_id: "0",
    //             guild_id: "0",
    //             author: {
    //                 id: "0",
    //                 name: "Loading...",
    //                 avatar: {
    //                     url: "bruh",
    //                     image: @image-url("../images/paicord_icon.png"),
    //                     loaded: true,
    //                 },
    //                 has_role_color: false,
    //                 role_color: Colors.aliceblue,
    //             },
    //             content: @markdown("Loading..."),
    //             timestamp: "yesteday at 12:00 PM",
    //             edited_timestamp: "",
    //          },
    //         kind: DiscordMessageKind.Default,
    //     }
    // ];

    callback select_channel(id: string);
    callback send_message(content: string);

    public function select_channel_slint(channel: DiscordChannel) {
        self.current_channel = channel;
        select_channel(channel.id);
    }

    public pure function channel_kind_to_icon(kind: DiscordChannelKind, open: bool) -> Icon {
        if kind == DiscordChannelKind.GuildText {
            return IconSet.Hash;
        } else if (kind == DiscordChannelKind.GuildVoice) {
            return IconSet.Volume2;
        } else if (kind == DiscordChannelKind.GuildCategory) {
            return open ? IconSet.ChevronDown : IconSet.ChevronRight;
        } else if (kind == DiscordChannelKind.GuildAnnouncement) {
            return IconSet.Megaphone;
        } else if (kind == DiscordChannelKind.GuildForum) {
            return IconSet.MessagesSquare;
        } else {
            return IconSet.Hash;
        }
    }
}