import {
    DiscordMessageSlint as DiscordMessage,
    DiscordMessageKindSlint as DiscordMessageKind,
} from "../../../../Models/DiscordMessage.slint";
import { LazyImage } from "../../../../Models/LazyImage.slint";
import { RoundedImage } from "../../../RoundedImage.slint";
import { VerticalBox, StyleMetrics, Palette } from "std-widgets.slint";
import { ImageGrid } from "../Attachments/ImageAttachment.slint";

export component DefaultMessage inherits Rectangle {
    in-out property <DiscordMessage> message;
    in-out property <bool> has-hover: false;
    background: has-hover || touch.has-hover ? Palette.background.brighter(0.2) : Palette.background;
    callback show-image(images: [LazyImage], index: int);

    HorizontalLayout {
        spacing: StyleMetrics.layout-spacing;
        RoundedImage {
            image-alignment: center;
            source: message.author.avatar.image;
            border-radius: 500px;
            image-width: 40px;
            image-height: 40px;
        }

        VerticalLayout {
            alignment: start;
            HorizontalLayout {
                spacing: StyleMetrics.layout-spacing;
                alignment: start;
                Text {
                    vertical-alignment: center;
                    text: message.author.name;
                    font-weight: 500;
                    font-size: 14px;
                    color: message.author.has_role_color ? message.author.role_color : Colors.white;
                }

                Text {
                    vertical-alignment: center;
                    text: message.timestamp;
                    font-size: 11px;
                    color: Palette.foreground.darker(0.4);
                }
            }

            if !message.empty: StyledText {
                text: message.content;
                font-size: 14px;
                wrap: TextWrap.word-wrap;
            }

            if message.image_attachments.length > 0: ImageGrid {
                images: message.image_attachments;

                show-image(images, index) => {
                    root.show-image(images, index)
                }

                changed has-hover => {
                    root.has-hover = self.has-hover;
                }
            }

        }
    }

    touch := TouchArea {
        z: -1;
    }
}
