import { Palette, StandardButton } from "std-widgets.slint";
import { CurrentUserStore } from "Globals/CurrentUserStore.slint";
import { AppStateSlint } from "State/AppState.slint";
import { LoginView } from "Common/Login/LoginView.slint";

//global state
export { CurrentUserStore, AppStateSlint }

//state globals
export { LoginManagerSlint } from "State/LoginManager.slint";

export component MainWindow inherits Window {
    icon: @image-url("images/paicord_icon.png");
    title: "Paicord";

    Rectangle {
        background: Palette.background;
    }

    preferred-height: 720px;
    preferred-width: 1280px;

    if CurrentUserStore.id == "" && AppStateSlint.ready: LoginView {

    }
}