import { Palette, StandardButton } from "std-widgets.slint";
import { CurrentUserStore } from "Globals/CurrentUserStore.slint";
import { AppStateSlint } from "State/AppState.slint";
import { LoginView } from "Common/Login/LoginView.slint";
import { LargeBaseplate } from "Baseplates/LargeBaseplate.slint";

//global state
export { CurrentUserStore, AppStateSlint }
export { GuildStore } from "Globals/GuildStore.slint";
export { ChannelStore } from "Globals/ChannelStore.slint";

//state globals
export { LoginManagerSlint } from "State/LoginManager.slint";

export component MainWindow inherits Window {
    icon: @image-url("images/paicord_icon.png");
    title: "Paicord";

    Rectangle {
        background: Palette.background;
    }

    preferred-height: 720px;
    preferred-width: 1280px;

    if CurrentUserStore.current_user.id == "" && AppStateSlint.ready: LoginView { }

    if CurrentUserStore.current_user.id != "" && AppStateSlint.ready: LargeBaseplate { }

    // LargeBaseplate {
        
    // }
}
